# Generated by Django 2.1 on 2020-02-05 16:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='tag',
            field=models.ManyToManyField(related_name='startup_tag', to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='startup.StartupCategory'),
            preserve_default=False,
        ),
    ]
