# Generated by Django 2.1 on 2020-02-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200206_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
    ]
