# Generated by Django 2.1 on 2020-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peed',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='peed.Tag'),
        ),
    ]
