# Generated by Django 2.1 on 2020-02-05 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peed', '0002_auto_20200206_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peed.Category')),
            ],
        ),
        migrations.AddField(
            model_name='peed',
            name='childCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='peed.ChildCategory'),
            preserve_default=False,
        ),
    ]
