# Generated by Django 2.1 on 2020-02-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peed', '0004_auto_20200206_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peed',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
